const data = { 
  subscriptionEmotes: 
  [ 'tonga',
    'pizza',
    'woman_with_headscarf',
    'spoon',
    'globe_with_meridians' ],
 customEmotes: 
  [ 'hearts',
    'train2',
    'congo_brazzaville',
    'turkmenistan',
    'benin',
    'shell',
    'pick',
    'woman_playing_water_polo',
    'face_with_head_bandage',
    'new_caledonia',
    'fu',
    'no_pedestrians',
    'cloud',
    'martinique',
    'rice',
    'blue_book',
    'yin_yang',
    'top',
    'billed_hat',
    'u6708',
    'liechtenstein',
    'gem',
    'norway',
    'checkered_flag',
    'woman_mechanic',
    'biohazard',
    'man_with_turban',
    'us_virgin_islands',
    'orthodox_cross',
    'sweet_potato',
    'thermometer',
    'hammer_and_wrench',
    'cloud_with_lightning_and_rain',
    'construction_worker_man',
    'school_satchel',
    'pouting_man',
    'fleur_de_lis',
    'shark',
    'latin_cross',
    'cd',
    'monkey_face',
    'u5408',
    'surfing_man',
    'hippopotamus' ],
 name: 'MyWhiteEltonXX',
 avatarPicUrl: 'https://loremflickr.com/80/80',
 backgroundPicUrl: 'https://bitztreambar.s3-us-west-1.amazonaws.com/HeartOutline.png',
 customEmotesCount: 44 };

 export default data;
 